//
//  LedLampPresenter.swift
//  Smarthome
//
//  Created by Richard Essemiah on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LedLampPresentationLogic {
	func presentSomething(response: LedLamp.Something.Response)
}

class LedLampPresenter: LedLampPresentationLogic {
	weak var viewController: LedLampDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: LedLamp.Something.Response) {
		let viewModel = LedLamp.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
