//
//  LedLampInteractor.swift
//  Smarthome
//
//  Created by Richard Essemiah on 11/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LedLampBusinessLogic {
	func doSomething(request: LedLamp.Something.Request)
}

protocol LedLampDataStore {
	//var name: String { get set }
}

class LedLampInteractor: LedLampBusinessLogic, LedLampDataStore {
	var presenter: LedLampPresentationLogic?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: LedLamp.Something.Request) {
//		worker = LedLampWorker()
//		worker?.doSomeWork()
		
		let response = LedLamp.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
