//
//  SmartPlugControlInteractor.swift
//  Smarthome
//
//  Created by Richard Essemiah on 14/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SmartPlugControlBusinessLogic {
	func doSomething(request: SmartPlugControl.Something.Request)
}

protocol SmartPlugControlDataStore {
	//var name: String { get set }
}

class SmartPlugControlInteractor: SmartPlugControlBusinessLogic, SmartPlugControlDataStore {
	var presenter: SmartPlugControlPresentationLogic?
	
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: SmartPlugControl.Something.Request) {
		let response = SmartPlugControl.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
