//
//  SmartPlugControlViewController.swift
//  Smarthome
//
//  Created by Richard Essemiah on 14/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SmartPlugControlDisplayLogic: class {
	func displaySomething(viewModel: SmartPlugControl.Something.ViewModel)
}

class SmartPlugControlViewController: UIViewController, SmartPlugControlDisplayLogic  {
	var interactor: SmartPlugControlBusinessLogic?
	var router: (NSObjectProtocol & SmartPlugControlRoutingLogic & SmartPlugControlDataPassing)?
	
	// MARK: Setup
	
	private func setup() {
		let viewController = self
		let interactor = SmartPlugControlInteractor()
		let presenter = SmartPlugControlPresenter()
		let router = SmartPlugControlRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing

	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		setup()
		doSomething()
		
		view.backgroundColor = .black.withAlphaComponent(0.7)
		view.isUserInteractionEnabled = true
	}
	
	override func viewDidLayoutSubviews() {
		super.viewDidLayoutSubviews()
		
		controlBackgroundView.layer.cornerRadius = controlBackgroundView.frame.width / 2
	}
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		let screenSize = UIScreen.main.bounds
		let screenWidth = screenSize.width
		let screenHeight = screenSize.height
		
		self.preferredContentSize = CGSize(width: screenWidth,
										   height: screenHeight * 0.3)
	}
	
	// MARK: Do something
	
	@IBOutlet weak var nameLabel: UILabel!
	@IBOutlet weak var controlView: UIView!
	@IBOutlet weak var controlBackgroundView: UIView!
	
	func doSomething() {
		let request = SmartPlugControl.Something.Request()
		interactor?.doSomething(request: request)
	}
	
	func displaySomething(viewModel: SmartPlugControl.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}
}

// MARK: View setup
private extension SmartPlugControlViewController {
	func setupLabels() {
		nameLabel.text = "Light"
		nameLabel.font = .camptonExtraBold(ofSize: 30)
		nameLabel.textColor = .white
	}
	
	func setupViews() {
		controlBackgroundView.backgroundColor = .black.withAlphaComponent(0.7)
		controlBackgroundView.clipsToBounds = true
	}
	
	func setupSlider() {
		
	}
}
