//
//  SingleRoomPresenter.swift
//  Smarthome
//
//  Created by Richard Essemiah on 01/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SingleRoomPresentationLogic {
	func presentRoomDevices(response: SingleRoom.FetchDevice.Response)
}

class SingleRoomPresenter: SingleRoomPresentationLogic {
	weak var viewController: SingleRoomDisplayLogic?
	
	// MARK: Present Room Device
	
	func presentRoomDevices(response: SingleRoom.FetchDevice.Response) {
		
		let devices: [SingleRoom.FetchDevice.ViewModel] = [
			SingleRoom.FetchDevice.ViewModel(name: "Light", deviceState: "On", type: .ledLamps),
			SingleRoom.FetchDevice.ViewModel(name: "Light", deviceState: "On", type: .ledStrips),
			SingleRoom.FetchDevice.ViewModel(name: "Smart TV", deviceState: "On", type: .smartPlugs),
			SingleRoom.FetchDevice.ViewModel(name: "Light", deviceState: "On", type: .ledLamps)
		]
		viewController?.displayDevices(viewModel: devices)
	}
}
