//
//  SingleRoomInteractor.swift
//  Smarthome
//
//  Created by Richard Essemiah on 01/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SingleRoomBusinessLogic {
	func doSomething(request: SingleRoom.FetchDevice.Request)
}

protocol SingleRoomDataStore {
	//var name: String { get set }
}

class SingleRoomInteractor: SingleRoomBusinessLogic, SingleRoomDataStore {
	var presenter: SingleRoomPresentationLogic?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: SingleRoom.FetchDevice.Request) {
		
		let response = SingleRoom.FetchDevice.Response()
		presenter?.presentRoomDevices(response: response)
	}
}
