//
//  SingleRoomRouter.swift
//  Smarthome
//
//  Created by Richard Essemiah on 01/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SingleRoomRoutingLogic {
	func routeBackToListRooms()
	func routeToLedControl()
	func routeToSmartPlugControl()
}

protocol SingleRoomDataPassing {
	var dataStore: SingleRoomDataStore? { get }
}

class SingleRoomRouter: NSObject, SingleRoomRoutingLogic, SingleRoomDataPassing {
	weak var viewController: SingleRoomViewController?
	var dataStore: SingleRoomDataStore?
	
	// MARK: Routing
	func routeBackToListRooms() {
		viewController?.dismiss(animated: true, completion: nil)
	}
	
	func routeToLedControl() {
		let vc = LedLampViewController()
		vc.modalPresentationStyle = .overFullScreen
		viewController?.present(vc, animated: true, completion: nil)
	}
	
	func routeToSmartPlugControl() {
		let vc = SmartPlugControlViewController()
		vc.modalPresentationStyle = .popover
		viewController?.present(vc, animated: true, completion: nil)
	}
}
