//
//  RoomsInteractor.swift
//  Smarthome
//
//  Created by Richard Essemiah on 31/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoomsBusinessLogic {
	func fetchRoom(request: Rooms.FetchRooms.Request)
}

protocol RoomsDataStore {
	//var name: String { get set }
}

class RoomsInteractor: RoomsBusinessLogic, RoomsDataStore {
	var presenter: RoomsPresentationLogic?
	
	//var name: String = ""
	
	// MARK: Do something
	
	func fetchRoom(request: Rooms.FetchRooms.Request) {
		let response = Rooms.FetchRooms.Response()
		presenter?.presentSomething(response: response)
	}
}
