//
//  RoomsRouter.swift
//  Smarthome
//
//  Created by Richard Essemiah on 31/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RoomsRoutingLogic {
	func routeToSingleRoom(room: String)
}

protocol RoomsDataPassing {
	var dataStore: RoomsDataStore? { get }
}

class RoomsRouter: NSObject, RoomsRoutingLogic, RoomsDataPassing {

	weak var viewController: RoomsViewController?
	var dataStore: RoomsDataStore?
	
	// MARK: Routing
	func routeToSingleRoom(room: String) {
		let vc = SingleRoomViewController()
		vc.singleRoom = room
		vc.modalPresentationStyle = .fullScreen
		viewController?.present(vc, animated: true, completion: nil)
	}
	
}
